[package]
name = "dec_from_char_gen"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0" 
description = "Gen package for dec_from_char library"

[dependencies]
csv = "1.3"
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }

[lib]
proc-macro = true
